### ISSUE TITLE
I wonder if Unyson Page Builder is using any cache option for image url?

### ISSUE THREAD

**Issue by thanhluu** [ThemeFuse/Unyson-Builder-Extension#6]
I have just changed URL of my site. After replacing url (via this tool https://github.com/interconnectit/Search-Replace-DB), pages built by Page Builder saw bug. However, when I edit such page then save, the bug disappeared.

I am not sure if Unyson did use any option that cache content of pages built by Page Builder? If yes, how can I refresh cache of these pages?

**Comment by valeriuzdrobau** [comment]
No, we have no option for caching images URLs,  after that this bug disappears, reappear the images? Because it's very likely that need to do some additional replaces like [here](https://github.com/ThemeFuse/Unyson-Backup-Extension/blob/master/includes/helpers/class-fw-backup-helper-database.php#L350-L381).

**Comment by thanhluu** [comment]
Thank for your answer! My issue has been resolved.
